# Spring Boot application config file

server: 
    address: 127.0.0.1   
    servlet:     
      session:       
        # see https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#server.servlet.session.timeout
        timeout: 2400
    tomcat:
        ajp:
           # see https://github.com/Evolveum/midpoint/blob/master/gui/admin-gui/src/main/java/com/evolveum/midpoint/web/boot/EmbeddedTomcatAutoConfiguration.java
           enabled: true
           port: 8009
           secret: "nwDKxIIEL6G6GTovoQbXzg"

